package uz.zero_one.project

enum class UserRole{
    ADMIN,OPERATOR,DIRECTOR,USER
}

enum class PermissionType {
    CREATE, READ, UPDATE, DELETE,SWITCH
}

enum class Status{
    ACTIVE,INACTIVE
}

enum class DownloadStatus{
    COMPLETED,INCOMPLETED
}

enum class ErrorCode(val code: Int){
    USER_NOT_FOUND(100),
    USER_NAME_ALREADY_EXISTS(101),
    ORGANISATION_NAME_EXISTS(102),
    USER_NAME_NOT_FOUND(103),
    ORGANISATION_NOT_FOUND(104),
    TEMPLATE_NOT_FOUND(105),
    CONTRACT_NOT_FOUND(106),
    ORGANISATION_NOT_ACTIVE(107),
    PASSWORD_NOT_FOUND(108),
    FILE_NOT_FOUND_EXCEPTION(109),
    TEMPLATE_KEY_NOT_FOUND_EXCEPTION(110),
    CONTRACT_VALUE_NOT_FOUND_EXCEPTION(111),
    FORBIDDEN_ROLE_EXCEPTION(112),
    ACCESS_DENIED_EXCEPTION(113),
    OPERATOR_PERMISSION_EXCEPTION(114)
}